### ISSUE TITLE
There was an error processing your request: No details were returned

### ISSUE THREAD

**Issue by skate28** [coleam00/bolt.new-any-llm#363] opened 2024-11-21 15:35 UTC
### Describe the bug

This error has been frustrating me and I am not able to use the software because of it. One day it works the next day this happens. What is wrong with it? I am on a Mac.

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by art3miz18** [comment] 2024-11-21 16:19
facing same issue running qwen 32B on ollama

**Comment by skate28** [comment] 2024-11-21 16:19
Thanks for confirmation, hopefully we can figure it out

**Comment by Elektra58** [comment] 2024-11-21 18:24
![image](https://github.com/user-attachments/assets/32a12697-6214-463f-8765-f3261277f795)
Same here, running qwen2.5-coder:7b and qwen2.5-coder:14b on Windows, neither works. Anthropic is fine.

**Comment by Elektra58** [comment] 2024-11-21 21:17
Potential duplicate of #259, see the fix there

**Comment by bekirisgor** [comment] 2024-11-22 14:26
Same issue here, also i got <boltaction at the end of file.

**Closed** 2024-12-02 15:11 UTC
